### ISSUE TITLE
Session loss after a very short time

### ISSUE THREAD

**Issue by hughmartin** [purestorage/PowerShell-Toolkit#20]
I don't know if this is expected behavior, but if I issue the Connect-PfaController statement and then issue a command once every 15 seconds, I can keep a session active (tested for 4 minutes).  However, if I don't issue a command for just over 60 seconds, when I run the command (in this case, the Get-PfaVolumes command, but every command I've tried does the same thing), the command returns no output and no error.  The fix would be to re-issue the Connect-PfaController command before every other command, but that's not a very elegant solution.  Here's the connect command I am using:

$objPSsession = Connect-PfaController -FlashArray $strPSarray -API_Token $objPStoken.api_token -HttpTimeOut 10000

I'm then issuing the Get-PfaVolumes and other commands with just the -Session parameter.

**Comment by barkz** [comment]
What version of the toolkit do you have installed? There was a bug pre-v2.8 that changed HttpTimeOut to a shorter value.

**Comment by hughmartin** [comment]
2.8.0.430

**Comment by barkz** [comment]
Hi Hugh - I have not been able to reproduce this condition. Can you modify the connection method to the following script and try.

$Sess = Get-PfaApiToken -FlashArray VALUE -Credential (Get-Credential) | Connect-PfaController -HttpTimeOut 12000

**Comment by hughmartin** [comment]
Same result.  See image.

(Embedded image moved to file: pic28503.gif)

Hugh Martin
Information Technology
Honda Manufacturing of Alabama, LLC
205.355.5269 (o,c)

**Comment by hughmartin** [comment]
For whatever it's worth.  I'm not sure what the IdleTimeout is, but the
issue I'm seeing occurs in less than 120 seconds.

Get-PfaConfiguration -Session $Sess | Select-Object
Version,Revision,IdleTimeout,Controllers | Format-List

Version     : 4.0.21
Revision    : 201504201827+02f76db
IdleTimeout : 120
Controllers : {@{status=ready; model=FA-420; version=4.0.21; name=CT0;
mode=primary}, @{status=ready; model=FA-420;
              version=4.0.21; name=CT1; mode=secondary}}


Hugh Martin
Information Technology
Honda Manufacturing of Alabama, LLC
205.355.5269 (o,c)


----- Forwarded by Hugh Martin/HMA/AM/HONDA on 05/14/2015 10:16 AM -----

From:	Hugh Martin/HMA/AM/HONDA
To:	purestorage/PowerShell-Toolkit <reply
            +00bd68f3caf6f5331c9262dc6737f5db55ad15a3fa79368692cf00000001116bceed92a169ce04898ee8@reply.github.com>
Date:	05/14/2015 07:13 AM
Subject:	Re: [PowerShell-Toolkit] Session loss after a very short time
            (#20)


Same result.  See image.

(Embedded image moved to file: pic29510.gif)

Hugh Martin
Information Technology
Honda Manufacturing of Alabama, LLC
205.355.5269 (o,c)

**Comment by barkz** [comment]
Morning Hugh - I have now reproduced this error. Looking at the $Error[0] stack:

```powershell
Invoke-RestMethod : The underlying connection was closed: An unexpected error occurred on a send.
At C:\Program Files\Pure
Storage\PowerShell\Modules\PureStoragePowerShellToolkit\PureStoragePowerShellToolkit.psm1:1082 char:11
+ ...     return (Invoke-RestMethod -Method Get -Uri $Uri -WebSession $Sess ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```
This is because the session token is timing out in 120 seconds. I need to work on a fix and will mark this as a bug. I am working on a 2.9 update to publish early next week.

Thanks,
barkz

**Comment by hughmartin** [comment]
Excellent.  Thanks for the update.

Hugh

**Comment by barkz** [comment]
I've done some further research on this issues and found that using netstat -an I can see the connections close unexpectedly. Further investigation finds this Active issue on Microsoft Connect (https://connect.microsoft.com/PowerShell/feedback/details/836732/tcp-connection-hanging-in-close-wait-when-using-invoke-restmethod-with-put-or-delete). This not only affects PUT, DELETE but also POST methods. I am working on changing the Try/Catch logic to address this short-coming using Invoke-RestMethod cmdlet.

**Comment by barkz** [comment]
After investigating this further and finally determining even with use of Invoke-WebRequest that the underlying issue is with Windows PowerShell.
