### ISSUE TITLE
MSI binary fails to install on Windows Server 2012 R1 

### ISSUE THREAD

**Issue by tlindsay42** [purestorage/PowerShell-Toolkit#5]
Error: This application requires PowerShell V3. Please install WinRM 3.0, then run this installer again.

![error](https://cloud.githubusercontent.com/assets/11078689/6329625/ad7fc12e-bb37-11e4-831c-6831650c246b.png)

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   6.3.9600.16406
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

PS C:\> Configure-SMRemoting.exe -Get
Server Manager Remoting is enabled

**Comment by barkz** [comment]
I created a Windows Server 2012 virtual machine. Copied the Pure Storage PowerShell 2.1.0.226 build and ran the install without an issue. See the screenshot which shows version information.

![pstkv3_ws2012](https://cloud.githubusercontent.com/assets/7435538/6333304/d00d6742-bb40-11e4-98e2-94ecd8c1d775.png)

**Comment by tlindsay42** [comment]
Correction: MSI binary fails to install on Windows Server 2012 R1 with PowerShell 4.0 upgrade installed (PowerShell 3.0 compatibility).  Note the PSVersion and PSCompatibleVersions differences.

PS C:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

PS C:\> $PSVersionTable.PSCompatibleVersions

Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      -1     -1
2      0      -1     -1
3      0      -1     -1
4      0      -1     -1

**Comment by barkz** [comment]
At this point I'm scratching my head. See my screenshot. I uninstalled PS PowerShell Toolkit from the same VM as I used previously. I downloaded PowerShell 4.0 via WMF4.0 (Windows8-RT-KB27998888-x64) and installed/restarted. Ran same installer for PS PowerShell Toolkit and voila it works no problems. When are you are installing are you admin? The installer requires administrative privileges. 

![git](https://cloud.githubusercontent.com/assets/7435538/6341983/82aeef84-bb86-11e4-9038-5aa471bc4727.png)

**Comment by barkz** [comment]
Hi Troy - Have you had a chance to check install permissions? Just wanted to check to see if we can close this issue out or not. 

Thanks,
barkz

**Comment by tlindsay42** [comment]
Hi barkz,

Q1. Have you had a chance to check install permissions?
A1. I am installing the binary as an administrator.

--
Troy Lindsay | FireHost
(US: +1) 877 262 3473 ext. 8468
(UK: +44) 0800 500 3167 ext. 8468

**Comment by tlindsay42** [comment]
Hi barkz, 

Q1. Have you had a chance to check install permissions? 
A1. I am installing the binary as an administrator.

Regards,
-Troy

**Comment by barkz** [comment]
Do you get an error message? With your account can you add Programs and Features? The installer will create the \Windows\System32\WindowsPowerShell\v1.0\Modules\PureStoragePowerShell folder and this cannot be done without permissions to perform the action. If you are an administrator this should be working properly. Can you try creating the folder manually and then download the files https://github.com/purestorage/PowerShell-Toolkit/blob/master/PureStoragePowerShell.psd1 and https://github.com/purestorage/PowerShell-Toolkit/blob/master/PureStoragePowerShell.psm1 then add them to the folder. Perform an Import-Module PureStoragePowerShell and let me know the outcome.

**Comment by tlindsay42** [comment]
Q1. Do you get an error message?
A1. Yep, the one originally posted.  

Q2. With your account can you add Programs and Features?
A2. Yes

I3. If you are an administrator this should be working properly. Can you try creating the folder manually and then download the files https://github.com/purestorage/PowerShell-Toolkit/blob/master/PureStoragePowerShell.psd1 and https://github.com/purestorage/PowerShell-Toolkit/blob/master/PureStoragePowerShell.psm1 then add them to the folder. Perform an Import-Module PureStoragePowerShell and let me know the outcome.
R3. 
PS C:\> Get-ChildItem -Recurse -Name C:\Windows\System32\WindowsPowerShell\v1.0\Modules\PureStoragePowerShell
PureStoragePowerShell.psd1
PureStoragePowerShell.psm1
PS C:\> Import-Module -Name PureStoragePowerShell
WARNING: The names of some imported commands from the module 'PureStoragePowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with  the Verbose parameter. For a list of approved verbs, type Get-Verb.

**Comment by barkz** [comment]
Then it is working. The WARNING you are seeing is because the toolkit uses a non standard verb "Eradicate". The Eradicate cmdlets are used to destroy volumes permanently from the FlashArray. It is a term we use in our CLI/Web Management GUI so I support it in the toolkit. 

I'm still confused about the install error but you now have the toolkit on your system at least. I'm going to close this issue now.

Thanks,
barkz

**Comment by tlindsay42** [comment]
Lame.  That is a workaround, but does not fix the issue with the binary.

Recover is also an unapproved verb.

PS C:\Users\tlindsay> Import-Module -Name PureStoragePowerShell -Verbose
VERBOSE: Loading module from path
'C:\Users\tlindsay\Documents\WindowsPowerShell\Modules\PureStoragePowerShell\PureStoragePowerShell.psd1'.
VERBOSE: Loading module from path
'C:\Users\tlindsay\Documents\WindowsPowerShell\Modules\PureStoragePowerShell\PureStoragePowerShell.psm1'.
...
VERBOSE: The 'Eradicate-PfaProtectionGroup' command in the PureStoragePowerShell' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
VERBOSE: Importing function 'Eradicate-PfaProtectionGroup'.
VERBOSE: The 'Eradicate-PfaVolume' command in the PureStoragePowerShell' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
VERBOSE: Importing function 'Eradicate-PfaVolume'.
...
VERBOSE: The 'Recover-PfaProtectionGroup' command in the PureStoragePowerShell' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
VERBOSE: Importing function 'Recover-PfaProtectionGroup'.
VERBOSE: The 'Recover-PfaSnapshot' command in the PureStoragePowerShell' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
VERBOSE: Importing function 'Recover-PfaSnapshot'.
VERBOSE: The 'Recover-PfaVolume' command in the PureStoragePowerShell' module was imported, but because its name does not include an approved verb, it might be difficult to find. For a list of approved verbs, type Get-Verb.
VERBOSE: Importing function 'Recover-PfaVolume'.
VERBOSE: The 'Refresh-PfaVolume' command in the PureStoragePowerShell' module was imported, but because its name does not include an approved verb, it might be difficult to find. The suggested alternative verbs are "Update".

**Comment by barkz** [comment]
This is the first time I've seen the particular problem you are facing. What does winrm get winrm/config output? Have you tried the latest installer 2.2.1.302 (https://github.com/purestorage/PowerShell-Toolkit/blob/master/PureStoragePowerShell_2_2_1_302.msi). 

Can you run Get-WindowsFeature | Where-Object { $_.Installed -eq $True } -- Screenshot shows what I have installed on the Windows Server 2012 instance.

![issue_5_getwinfeature](https://cloud.githubusercontent.com/assets/7435538/6456965/586b3948-c122-11e4-82d6-40a794e6316e.png)

**Comment by tlindsay42** [comment]
Hi barkz,

Sorry for the delay.  I just tried the latest binary- PureStoragePowerShell_2_3_0_305.msi and it installed as expected and with no issues, so whatever the issue was has been patched.  Closing ticket.  Thanks!

Regards,
-Troy
